StudyDjango/urls.py
from django.conf.urls import url
from django.contrib import admin
from  django.conf.urls import include
from django.contrib.sitemaps .views import sitemap
from myblog.sitemaps import PostSitemap

sitemaps={
    'posts':PostSitemap,
}
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myblog/', include('myblog.urls',namespace='myblog',app_name='myblog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

myblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .feeds import LastestPostsFeed

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w \t]+)/$',views.post_detail,name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share,name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
    url(r'^feed/$', LastestPostsFeed, name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

myblog/models.py
#coding:utf-8

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
#标签包
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    '''
    实体－文章类
    发布的文章
    '''
    STATUS_CHOICES={
        ('draft', '草稿'),
           ('published', '发布'),
    }
    title=models.CharField(max_length=300,verbose_name='文章标题')
    zhaiyao=models.TextField(verbose_name='摘要')
    content=models.TextField(verbose_name='文章内容')
    author = models.ForeignKey(User,related_name='blog_posts')
    publish = models.DateTimeField(default=timezone.now,verbose_name='发布时间')
    created = models.DateTimeField(auto_now_add=True,verbose_name='提交时间')
    updated = models.DateTimeField(auto_now=True,verbose_name='更新时间')
    status=models.CharField(max_length=10,choices=STATUS_CHOICES)
    objects=models.Manager()
    tags=TaggableManager
    published=PublishedManager()
    # #分类标签
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:post_detail',args=[self.publish.year,
                                self.publish.strftime('%m'),
                                self.publish.strftime('%d'),
                                self.title.encode('utf-8')])

class Comment(models.Model):
    '''
    文章的评论
    '''
    #一对多的关系 一个文章有多条评论 评论的主体来自文章
    post = models.ForeignKey(Post, related_name='comments')
    #名称
    name = models.CharField(max_length=80)
    #邮件
    email = models.EmailField()
    #评论内容
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

myblog/forms.py
#coding:utf-8
__author__ = 'similarface'
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25,label='姓名    ')
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea,label='备注')

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('name','email','body')

class SearchForm(forms.Form):
    '''
    查询框
    '''
    query=forms.CharField(label='关键字')

myblog/views.py
#coding:utf-8
from django.shortcuts import render
#404
from django.shortcuts import get_object_or_404
#分页模块
from django.core.paginator import PageNotAnInteger,EmptyPage,Paginator
# Create your views here.
from .models import Post
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
#邮件模块
from django.core.mail import send_mail
from django.db.models import Count

#标签
from taggit.models import Tag
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

def post_list(request,tag_slug=None):
    '''
    文章的列表
    :param request:
    :return:所有文章的列表
    '''
    #获取所有的published的文章

    object_list=Post.published.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        object_list=object_list.filter(tags__in=[tag])
    paginator=Paginator(object_list,3)
    #rquest没有就返回None
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'myblog/post/list.html',{'page':page,'posts':posts,'tag':tag})


def post_detail(request,year,month,day,post):
    '''
    文章详情
    +
    评论详情
    :param request:
    :param year:文章发布的年份
    :param month:文章发布的月份
    :param day:文章发布day
    :param post:文章标题
    :return:匹配的具体对象
    '''
    post=get_object_or_404(Post,title=post)
    #post.comments 的来源 ==> related_name='comments'
    comments=post.comments.filter(active=True)
    new_comment=None
    if request.method=='POST':
        comment_form=CommentForm(data=request.POST)
        if comment_form.is_valid():
            #不会存入数据库
            new_comment=comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form=CommentForm()
    # 列出相似的文章
    #获取文章post的标签
    post_tags_ids = post.tags.values_list('id', flat=True)
    #过滤其他的文章排除本事
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    #
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return render(request,'myblog/post/detail.html',{'post':post,
                                                     'comments': comments,
                                                     'comment_form':comment_form,
                                                     'new_comment':new_comment,
                                                     'similar_posts': similar_posts
                                                     })

def post_share(request,post_id):
    '''
    文章分享 发送邮件
    '''
    post=get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method=='POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url=request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) 推荐你阅读 "{}"'.format(cd['name'], cd['email'], post.title)
            message = '阅读: "{}" 地址: {}\n\n{}\ 备注: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            #这儿的yangwubing@23mofang.com 要和settings.py的EMAIL_HOST_USER 对应
            send_mail(subject, message, 'yangwubing@23mofang.com',[cd['to']])
            sent = True
    else:
        form=EmailPostForm()
    return render(request, 'myblog/post/share.html', {'post': post,'form': form,'sent': sent})


class PostListView(ListView):
    '''
    对象列表返回类 分页 包装
    '''
    #查询结果集
    queryset = Post.published.all()
    #对象容器
    context_object_name = 'posts'
    #分页大小
    paginate_by = 3
    #定向到那个模版
    template_name = 'myblog/post/list.html'


from .forms import SearchForm
from haystack.query import SearchQuerySet
# def post_serarch(request):
#     '''
#     文章搜索
#     :param request:
#     :return:
#     '''
#     form = SearchForm()
#     if 'query' in request.GET:
#         form=SearchForm(request.GET)
#         if form.is_valid():
#             cd=form.cleaned_data
#             results=SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
#             total_results=results.count()
#             for result in results:
#                 pass
#
#             return render(request,'myblog/post/search.html',{'form':form,'cd':cd,'results':results,'total_results':total_results})
#     return render(request,'myblog/post/search.html',{'form':form})

def post_search(request):
    '''
    文章搜索
    :param request:
    :return:
    '''
    form = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query'])#.load_all()
            #.load_all()
            # count total results
            total_results = results.count()
            for result in results:
                a=result.object

            return render(request, 'myblog/post/search.html', {'form': form,
                                                     'cd': cd,
                                                     'results': results,
                                                     'total_results': total_results})
    return render(request, 'myblog/post/search.html', {'form': form})

myblog/templates/myblog/post/detail.html
{% extends 'myblog/base.html' %}
{% load blog_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
        <p class="date">
            posted@{{ post.publish }} {{ post.author }}
            <a href="{% url "myblog:post_share" post.id %}">分享文章</a>
        </p>
{#    {{ post.content|linebreaks }}#}
    {{ post.content| markdown}}

    <!-- 推荐类似文章 -->
     <h2>相似文章</h2>
        {% for post in similar_posts %}
     <p>
         <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
     </p>
        {% empty %}
        没有类似的文章。
        {% endfor %}
    <!-- 文章评论 -->
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} 条评论。 {{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
        <p class="info">
            评论: {{ forloop.counter }}&nbsp;{{ comment.name }}&nbsp;{{ comment.created }}
        </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>没有任何评论.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>你写的评论已经提交.</h2>
    {% else %}
        <h2>评论下吧</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="提交"></p>
        </form>
    {% endif %}
{% endblock %}

myblog/templates/myblog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

myblog/templates/myblog/post/list.html
{% extends "myblog/base.html" %}
{% load blog_tags %}
{% block content %}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="tags">
            {#            {{ post.tags.all|join:", " }}#}
            标签:
            {% for tag in post.tags.all %}
                <a href="{% url "myblog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}
                    ,
                {% endif %}
            {% endfor %}
        </p>
        {#        posted @ 2016-04-18 16:16 similarface#}
        <p class="date">
            posted@{{ post.publish }} {{ post.author }}
        </p>
        {#        {{ post.body|truncatewords:30|linebreaks }}#}
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
    {#    {% include "pagination.html" with page=page_obj %}#}
{% endblock %}

myblog/templates/myblog/post/search.html
{% extends "myblog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% for result in results %}
        	{% with post=result.object %}
        		<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.content|truncatewords:5 }}
        	{% endwith %}
        {% empty %}
        	<p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "myblog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

myblog/templates/myblog/post/share.html
{% extends "myblog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>邮件发送成功</h1>
        <p>
            "{{ post.title }}" 已经成功发送到 {{ cd.to }}.
        </p>
    {% else %}
        <h1>分享文章 "{{ post.title }}" </h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="发送邮件">
        </form>
    {% endif %}
{% endblock %}